name: Test Hasura

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HASURA_GRAPHQL_ENDPOINT: http://127.0.0.1:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build CLI
        run: go build -o ./hasuraenv cmd/hasuraenv/hasuraenv.go

      - name: init hasuraenv
        run: ./hasuraenv init

      - name: Add Path
        run: export PATH=~/.hasuraenv/current:$PATH;

      - name: Use hasura-cli
        run: hasura version
