name: Static Check

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      # https://github.com/golangci/golangci-lint/issues/3107
      - name: SET GOROOT
        run: |
          echo "GOROOT=${{ go env GOROOT }}" >> $GITHUB_ENV

      - name: Minimize Module
        run: |-
          go mod tidy
          git diff --exit-code

      - name: Format Check
        run: |-
          go fmt ./...
          git diff --exit-code

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
