name: Test

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build binary for e2e testing
        run: make build-for-e2e-test

      - name: e2e testing
        run: make e2e-testing
